name = "cyberbard-index"
compatibility_date = "2024-03-29"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cyberbard-index-db"
database_id = "38616ff5-1f79-414e-a8bf-380895e7af2c"
